#!/usr/bin/env bash
# Update the package list
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Create a simple HTML file that contains "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Add redirection to /redirect_me in the nginx default site configuration
grep -qxF '    return https://www.youtube.com$request_uri;' /etc/nginx/nginx.conf || sudo sed -i '/listen 80;/a\    return https://www.youtube.com$request_uri;' /etc/nginx/nginx.conf
# Restart nginx to apply the changes
sudo systemctl restart nginx

# Confirm nginx is serving the correct page and the redirection works
curl -sI http://localhost/redirect_me/

