#!/usr/bin/env bash
# Stop to infinity program

pid=$(pgrep -f "4-to_infinity_and_beyond")

# If the process is running, terminate it
if [ -n "$pid" ]; then
	kill -SIGTERM $pid
else
	echo "4-to_infinity_and_beyond process is not running"
fi
