#!/usr/bin/env bash
# Display hours from 0-12
# Display minutes from 1 to 59

hour=0
minutes=1

while [ $hour -lt 13 ]
do
	echo "Hour: $hour"
	while [ $minutes -lt 60 ]
	do
		echo $minutes
		((minutes++))
	done
	((hour++))
	minutes=1
done
